### ISSUE TITLE
Should we throw an error when disposing multiple times?

### ISSUE THREAD

**Issue by flut1** [mediamonks/seng-destructible#2]
A lot of implementations might fail when being disposed multiple times. Say for example, the dispose() method removes an element from the DOM:
```
this.element.parentNode.removeChild(this.element);
```
We used to guard against these duplicate calls using a construction like so:
```
if (this.element) {
  this.element.parentNode.removeChild(this.element);
  this.element = null;
}
```
However, this is now often no longer possible. This is because a lot of our projects now use the `strictNullChecks` option, which does not allow a property like `this.element` to be set to `null` unless it has explicitly been defined as nullable. 

Should we for that reason throw an error when attempting to call the dispose method for the second time? We might be able to achieve this by overwriting the dispose method like so:

```
function throwAlreadyDisposed():void {
  throw new Error('Cannot call the dispose() method twice');
}

public dispose():void {
  this.disposed = true;
  this.dispose = throwAlreadyDisposed;
}
```

**Comment by ThaNarie** [comment]
This is a tricky one. The whole reason for the `if` checks is to **not** have errors on cleaning up stuff when called twice, which sometimes _could_ happen in a normal-ish situation.

If we intentionally throw errors it defeats that purpose.

Another solution could be to have a `if (this.disposed) super.dispose();` check at the top of the function.

Just to be sure, this is only about things that are non-nullable, right? In cases where an element could still be set, the typing would be nullable, and the checks would be allowed, right?

**Comment by flut1** [comment]
> This is a tricky one. The whole reason for the if checks is to not have errors on cleaning up stuff when called twice, which sometimes could happen in a normal-ish situation.

I'm not sure this is very evident. Regardless of what we go for, it might be a good idea anyway to clearly state in the (api) documentation if the `dispose()` method is supposed to be called multiple times or not.  I would say from a conceptual perspective, it doesn't make sense to dispose multiple times. 

> Another solution could be to have a if (this.disposed) super.dispose(); check at the top of the function.

This would require all implementing classes to add the check right? Because the super call is at the end, the statements in higher level classes will be called first.

> Just to be sure, this is only about things that are non-nullable, right? In cases where an element could still be set, the typing would be nullable, and the checks would be allowed, right?

Yes. Or if `undefined` is an allowed value, you might do `delete this.someProperty;` in `dispose()`. I would want to prevent situations though were we encourage to make things nullable if otherwise not necessary.

**Comment by ThaNarie** [comment]
> if the dispose() method is supposed to be called multiple times or not. I would say from a conceptual perspective, it doesn't make sense to dispose multiple times.

Of course the intention is to only have it called once, but there could be situation where two objects have references to the same other objects, and both call the destruct. Of course this should be spotted during development, but still the question remains; should an app break of cleanup breaks?

> This would require all implementing classes to add the check right? Because the super call is at the end, the statements in higher level classes will be called first.

Correct, something we do not really want. But maybe only in the cases where you cal dispose an another object from the outside (to solve the situation above).

>  I would want to prevent situations though were we encourage to make things nullable if otherwise not necessary.

Of course, the only cases where you really want to null something in the destruct, are references to outside objects (that could keep the other object alive). Where a reference is passed in or something.
All the other cases are purely to make it a bit easier for the GC, since the 'chains' between objects are broken, it's more easy to isolate and clean them.

**Comment by flut1** [comment]
> All the other cases are purely to make it a bit easier for the GC, since the 'chains' between objects are broken, it's more easy to isolate and clean them.

I'm still not entirely convinced by this argument. Would like to see some data or some kind of technical write-up that supports this notion. I do understand that, _given we accidentally forget to dereference an object_, 'nulling' will minimize the damage because that object will have less references to other objects. But as far as performance gains in normal situations I'm not convinced yet. I could go into why, but if you already happen to know some reading material on the issue already that would help

**Comment by flut1** [comment]
> Of course this should be spotted during development, but still the question remains; should an app break of cleanup breaks?

What do you think about a softer approach to prevent this from breaking an otherwise working application? So still replace the `dispose()`, but instead of throwing we do an error log and return

**Comment by ThaNarie** [comment]
> I do understand that, given we accidentally forget to dereference an object, 'nulling' will minimize the damage because that object will have less references to other objects.

Yeah, that. It indeed doesn't matter how chained they are. Only objects that are still referenced by root objects (globals, DOM, etc) are kept, all others are removed. It's mostly a precaution.

http://jayconrod.com/posts/55/a-tour-of-v8-garbage-collection

I can think of two situations:

1. A chain of objects is disposed from another class, but it forgets to set the reference to null there. This results in the complete chain is still referenced, so won't be GC'd. If you would do null-reffing in all destructs, it would only keep the first object in memory, not the rest.

2. After disposing a chain, one of the objects in the chain could still be referenced from another location. It might even call methods on those disposed objects. When that happens it also keeps the chain from that point in memory, but it could also execute code that shouldn't happen. If we would null-ref everything, we probably would get a runtime error when a nulled object is referenced in a called method. At least you'll catch the error earlier, otherwise you might not have spotted the potential memory leak and code kept getting executed on the background.

So it does have it's value, but not sure how we important we think it is.

> What do you think about a softer approach to prevent this from breaking an otherwise working application? So still replace the dispose(), but instead of throwing we do an error log and return

I would like that approach :)

Note that we are talking about multiple things here:
1. should we set everything to null? (doesn't work nicely together with TS)
2. should dispose be allowed called twice (will only be an issue if we keep setting things to null without checking)

**Comment by flut1** [comment]
Some questions and remarks about the above. I don't necessarily disagree with everything you say but I think it's worth a critical look

> http://jayconrod.com/posts/55/a-tour-of-v8-garbage-collection
...
So it does have it's value

I actually had read up on some of v8's garbage collection before and watched a talk about it, so I'm not completely unfamiliar with the concepts. What I meant to ask about was writing about this specific problem, not the general workings of a GC. 

I get how on an intuitive level you might argue that less pointers between objects means less work for the GC. However, I **a)** haven't found any conclusive text that this is actually true and **b)** that this difference is not trivial to the point of not worth consideration. 

Given that JS is an object orientated language, a lot of modern libraries work with large objects with lots of references in between them. Yet I haven't seen wide-spread adoption of a best practice to null every single reference property on those objects before dereferencing the object itself (though correct me if I'm wrong here). If nulling really resulted in considerable performance gain, wouldn't it be more widely adopted?

>  If we would null-ref everything, we probably would get a runtime error when a nulled object is referenced in a called method. At least you'll catch the error earlier, otherwise you might not have spotted the potential memory leak and code kept getting executed on the background.

Is a runtime error really always better than a memory leak? During development, sure. But in production?

> So it does have it's value, but not sure how we important we think it is.

I would argue not just how important it is, but what the possible cons are. Besides possibly unnecessarily bloating our code, I think without context it might give a wrong impression to new developers about what setting to null actually does.

**Comment by ThaNarie** [comment]
> I get how on an intuitive level you might argue that less pointers between objects means less work for the GC.

I agreed with you in the previous comment **"Yeah, that. It indeed doesn't matter how chained they are."** It only helps when dealing with mistakes. :)

> Is a runtime error really always better than a memory leak? During development, sure. But in production?

I guess it depends. It's not always a memory leak though, it could also be that code keeps on executing logic that shouldn't happen, resulting in weird behaviour.
